services:
  db:
    image: postgres:16-alpine
    container_name: impulse_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: impulse_user
      POSTGRES_PASSWORD: impulse_password
      POSTGRES_DB: impulse_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  backend:
#    build: ./src/backend/
##    env_file:
##      - .env
#    container_name: impulse_backend
#    restart: unless-stopped
#    ports:
#      - "5000:5000"
#    environment:
#      - SECRET_KEY=dev-secret-key-change-in-prod
#    depends_on:
#      - db

volumes:
  postgres_data:
