spring.application.name=impulse


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/impulse_db}
spring.datasource.username=${DB_USER:impulse_user}
spring.datasource.password=${DB_PASSWORD:impulse_password}

spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.open-in-view=false

spring.session.jdbc.table-name=SESSIONS