spring.application.name=impulse


spring.datasource.url=jdbc:postgresql://localhost:5432/impulse_db
spring.datasource.username=impulse_user
spring.datasource.password=impulse_password

spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.open-in-view=false