@startuml
title Streaming a track

actor User as user
participant "Web client /\nother client" as client
box "Docker (compose)" #EEEEEE
  participant "Backend\n(Spring Boot)" as api
  participant "Redis" as redis
  database "PostgreSQL" as db
end box
participant "SeaweedFS\n(S3 compatiable storage)" as storage

user -> client : press play
client -> api : GET /api/v1/tracks/{id}/playlist.m3u8
api -> redis: increment counter, check limit
alt spam
   redis-->api: spam
   api--> client: 429 too many requests
else allow
   redis --> api: proceed
   api -> api : check visibility and login

alt not allowed (private item, anonymous)
  api --> client : 404 Not Found
else allowed
  api -> db : find file path, and it's status
  db --> api : return path
  api -> storage : get file by path
  storage --> api : return file (.m3u8)
  api --> client : 200 OK (HLS playlist)
loop until stream ends
  client -> api: GET /api/v1/tracks/{id}/segments/{n}
  api -> storage: get N segment
  storage --> api: return N segment
  api --> client: play N segment
end
end
end

client --> user : audio plays
@enduml