@startuml
title Uploading a track

actor User as user
participant "Web client /\nother client" as client
box "Docker (compose)" #EEEEEE
  participant "Backend\n(Spring Boot)" as api
  participant "FFmpeg\n(process)" as ffmpeg
  database "PostgreSQL" as db
end box
participant "Library folder\n(volume)" as storage

user -> client : upload file
client -> api : POST /api/v1/upload?uploadinfo=info.json
api -> api : check permissions and login

alt not allowed (anonymous)
  api --> client : 401/403 not authorized \nor authenticated.
else allowed
  api -> api: check file integrity
  alt file's not valid
  api --> client: 415 Unsupported Media Type
  else
  api -> storage: dedicate place for a file and store it
  storage --> api: return uuid
  end
  alt if metadata exists
  api -> ffmpeg: exctract metadata trough ffprobe
  ffmpeg --> api: return metadata
  api -> db: write path, codec and metadata
  else if metadata not found
  api -> db: write path, codec and filename
  db --> api: ok
  end
  api --> client: 201 Created
end

client --> user : "file uploaded successfully"
@enduml